### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by UO289930** [Arquisoft/wiq_en3a#117]
Hi Pablo

We are still having problems to deploy the application. Now, all the images are successfuly created and runned on the azure virtual machine, but we are having problems with the gateway connection. Would you mind helping us with that, please.

Thanks in advance

**Comment by pglez82** [comment]
I  need more information. In which branch is the code, what is exactly the problem, is the webapp not connecting to the gatewayservice? It it working in docker locally?

**Comment by UO289930** [comment]
It is actually deployed in docker in the virtual marchine (the IP is 51.103.210.249), but once the gateway service is called at an endpoint that uses any other service, it breaks. The code is in develop branch

**Comment by pglez82** [comment]
Did you try to see if the endpoint works using some kind of tool like postman or curl? You can test individual endpoints to see what might be failing. I am not totally sure but it seams that the webapp configuration is ok, so I would discard this part of the application for now and focus the efforts in the services.

What I would do is:

1) Open port 7259 and 8002 temporarily in the remote machine.
2) Check a call to the userservice or/and wikidata_service using postman to see that they are working.
3) If this work, you know that this services are working ok. Now its time to check the gatewayservice. Print the process.env.WIKIDATA_SERVICE_URL variable in the /WikiData/GetCapitalsQuestions method and call it using the browser (checking the console).
4) Make sure that it is pointing to the wikidata_service.

Tell me the results of this tests, and let me know if you find the problem.

An extra note:
One thing I do not like is in the release.yml you have the API_URI argument for all the images. Only the webapp has this argument in the Dockerfile.
