### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by UO289930** [Arquisoft/wiq_en3a#153]
Hi Pablo

We are having some problems with the tests.  Once we run the test I show below, we get an strange error related to the object Console not having its function (console.log, console.error). We have another test that is more or less the same but works. We have been trying for some time but we did not get anything.

Code test:
![code_test](https://github.com/Arquisoft/wiq_en3a/assets/124297960/28920909-2e8e-4d8f-b9da-b6b097a1cfc1)

Error:
![erorr_test](https://github.com/Arquisoft/wiq_en3a/assets/124297960/8b02ef60-1a7e-459b-a2df-6a30c347efa9)

Thanks in advance

**Comment by pglez82** [comment]
I would need the branch in which the code is and the specific test file.

**Comment by UO289930** [comment]
It is in the branch "separate_api_and_test" at /gatewayservice/gateway-service.test.js. The test that causes problems is the test for the endpoint /getCapitalsQuestions.

**Comment by pglez82** [comment]
You are missing mocking up the get petitions for this call:

```javascript
axios.get.mockImplementation((url) => {
    if (url.endsWith('/getQuestions') || url.endsWith('/getCapitalsQuestions')) {
      return Promise.resolve({ 
        status: 200,
        data: [your 10 mocked questions] 
      });
    } 
  });
```

**Comment by UO289930** [comment]
We still don't get the results expected for Get operations. It seems that the gateway still tries to call the wikidata service and gives an error, so somehow the request mocking works for Post request, but not for Get requests.

**Comment by pglez82** [comment]
I tested in the branch that you told me and it and it fails because I didn't fill the data, but the get petition is returning a code 200 and the mocking is working well:

![imagen](https://github.com/Arquisoft/wiq_en3a/assets/10683040/18a45486-6054-4a15-8e6c-9d22a979d82b)
