### ISSUE TITLE
Alberto - Self report 3

### ISSUE THREAD

**Issue by Alberto-Guerra** [Arquisoft/wiq_en3a#165]
The third sprint saw me continue in a leadership role, while still contributing to development tasks

My primary development focus this sprint was on ensuring the quality of the frontend by unit testing individual components

We again as a team did a lot of pair programming, so i also took part in some parts of the testing of the wikidata service and some fixes and upgrade in the user interface.

issues: 
- #25 
- #140 
- #142 
- #143
- #145 

Important commits: 
- https://github.com/Arquisoft/wiq_en3a/commit/63672af4ce56fb4c3a75e93f64ae315bc55d9472
- https://github.com/Arquisoft/wiq_en3a/commit/b66c49a234945883299bf97484ad6092c09fe29e
- https://github.com/Arquisoft/wiq_en3a/commit/426eed4da7e9baf3cc83e6bb4ac8fdf346f32883
- https://github.com/Arquisoft/wiq_en3a/commit/f62860fc4c3f2a038cc31681fe64837d42e0779d

**Comment by pglez82** [comment]
**Important**: this self-report should be improved including also links not only to issues but to specific pull requests or commits that clearly show your contributions in the repository.

**Comment by Alberto-Guerra** [comment]
Links to commits added
