### ISSUE TITLE
Rita - Self report 3

### ISSUE THREAD

**Issue by ritacatuxo** [Arquisoft/wiq_en3a#170]
In this sprint I did the the tests for the user management, modificating the user-service and auth-service accordingly for them. I also created the openAPI documentation for user service, and updated the documentation.

Issues:
https://github.com/Arquisoft/wiq_en3a/issues/120
https://github.com/Arquisoft/wiq_en3a/issues/127
https://github.com/Arquisoft/wiq_en3a/issues/145

Pull requests:
https://github.com/Arquisoft/wiq_en3a/pull/157
https://github.com/Arquisoft/wiq_en3a/pull/161
https://github.com/Arquisoft/wiq_en3a/pull/155

**Comment by pglez82** [comment]
**Important**: this contribution issue should be improved including also links not only to issues but to specific pull requests or commits that clearly show your work in the repository.
