### ISSUE TITLE
Problem releasing e2e test

### ISSUE THREAD

**Issue by sergiollende** [Arquisoft/wiq_en3a#178]
Hi Pablo,

We have already deployed our application but when we try to do the release with the e2e test, they always failed. Locally they are working perfectly so we don't understand why they are not passing.
You can see the error in the last release:
- https://github.com/Arquisoft/wiq_en3a/actions/runs/8637901655

**Comment by pglez82** [comment]
If I say that I am going to check you project for this release on Thursday at 9am, It makes not sense to assign me an issue at 23:38 the day before. We can comment this problem and its solution after the revision in the lab session today.
